package com.canteen.app.deletion;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ListView;
import android.widget.Toast;

import com.example.microtemp.microblog.R;

import java.util.ArrayList;

public class  AdditionsActivity extends AppCompatActivity {
    private ArrayList<String> list = new ArrayList<String>(); //Initialize ArrayList with String data type
    Intent mIntent;
    static int actPostion;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_additions);


        ListView mlistview = (ListView) findViewById(R.id.additions_lv);


        //    System.out.println(videos.get(0).getFoods().get(0).getAdditions().size());
        for(int i=0;i<TypeDishActivity.menu.get(TypeDishActivity.actPostion).getFoods().get(FoodListActivity.actPostion).getAdditions().size();i++) {
            list.add(TypeDishActivity.menu.get(TypeDishActivity.actPostion).getFoods().get(FoodListActivity.actPostion).getAdditions().get(i).getName()+
                    "\n"+TypeDishActivity.menu.get(TypeDishActivity.actPostion).getFoods().get(FoodListActivity.actPostion).getAdditions().get(i).getPrice()); //Add one String into the ArrayList list//Add another one String into the ArrayList list
        }

        ArrayAdapter<String> mArrayAdapter = new ArrayAdapter<String>(this,
                android.R.layout.simple_list_item_1, list); //Use the build-in view list that provided by ArrayAdapter
        mlistview.setAdapter(mArrayAdapter);

        mlistview.setOnItemClickListener(new AdapterView.OnItemClickListener() {

            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position,
                                    long id) { //This is automatically generated by the OnItemClickListener, the parameters are shown as the default name says, so we can assign the "position" in the next progress.
                // TODO Auto-generated method stub

                AdditionsActivity.actPostion = position;
                Toast.makeText(AdditionsActivity.this, Integer.toString(position), Toast.LENGTH_SHORT).show();
                Toast.makeText(AdditionsActivity.this, "Order Accepted", Toast.LENGTH_SHORT).show();
                mIntent = new Intent(AdditionsActivity.this, TypeDishActivity.class);
                startActivity(mIntent);
            }
        });
    }


}




