package com.example.microtemp.microblog.deletion;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ListView;
import android.widget.Toast;

import com.example.microtemp.microblog.R;
import com.example.microtemp.microblog.api.Request;
import com.example.microtemp.microblog.api.ServiceCallback;
import com.example.microtemp.microblog.api.data.Example;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.reflect.TypeToken;

import java.util.ArrayList;
import java.util.List;

import static android.widget.AdapterView.*;

public class TypeDishActivity extends AppCompatActivity implements ServiceCallback {
    private ArrayList<String> list = new ArrayList<String>(); //Initialize ArrayList with String data type
    Intent mIntent;
    static    List<Example> menu;
    static int actPostion;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        // TODO Auto-generated method stub
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_type_dish);



        Request request=new Request(this);
        request.uruchom("http://212.191.92.88:51010/menu");



    }

    @Override
    public void serviceSucces(String json){
     Gson gson = new GsonBuilder().create();

    ListView mlistview = (ListView) findViewById(R.id.dish_lv);

        TypeDishActivity.menu = gson.fromJson(json, new TypeToken<List<Example>>(){}.getType());

        //    System.out.println(videos.get(0).getFoods().get(0).getAdditions().size());
    for(int i=0;i<menu.size();i++) {
        list.add(menu.get(i).getName()); //Add one String into the ArrayList list//Add another one String into the ArrayList list
    }

        ArrayAdapter<String> mArrayAdapter = new ArrayAdapter<String>(this,
                android.R.layout.simple_list_item_1, list); //Use the build-in view list that provided by ArrayAdapter
        mlistview.setAdapter(mArrayAdapter);

        mlistview.setOnItemClickListener(new OnItemClickListener(){

            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position,
                                    long id) { //This is automatically generated by the OnItemClickListener, the parameters are shown as the default name says, so we can assign the "position" in the next progress.
                // TODO Auto-generated method stub

                TypeDishActivity.actPostion=position;
                Toast.makeText(TypeDishActivity.this, Integer.toString(position), Toast.LENGTH_SHORT).show();
                    mIntent = new Intent(TypeDishActivity.this, FoodListActivity.class);
                    startActivity(mIntent);
                }




        });
    }

    @Override
    public void serviceFailure(Exception e) {

    }
}